services:
  auth-db:
    container_name: chatting_auth-db
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME:-chatting_auth}
      POSTGRES_USER: ${AUTH_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD:-postgres}
    ports:
      - ${AUTH_DB_PORT:-5432}:5432
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - chatting_network

  user-db:
    container_name: chatting_user-db
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: ${USER_DB_NAME:-chatting_user}
      POSTGRES_USER: ${USER_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD:-postgres}
    ports:
      - ${USER_DB_PORT:-5434}:5434
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - chatting_network

  rabbitmq:
    container_name: chatting_rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBIT_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    ports:
      - ${RABBITMQ_PORT:-5672}:5672
      - ${RABBITMQ_MANAGEMENT_PORT:-15672}:15672
    networks:
      - chatting_network

volumes:
  auth-db-data:
  user-db-data:

networks:
  chatting_network:
    driver: bridge
